baseurl = "https://redmmt.cr/"
title = "Red MMT Costa Rica"
copyright = "Copyright &copy; 2020 - Red MMT Costa Rica"
canonifyurls = true
theme = "tale"
paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true


DefaultContentLanguage = "es"

enableRobotsTXT = true

[languages]
  [languages.es]
    title = "Red MMT Costa Rica"
    languageName = "Spanish"
    weight = 1
[params]
  css = ["css/index.css", "https://fonts.googleapis.com/css2?family=Roboto&display=swap"]
