baseurl = "https://vigorous-newton-ee14bd.netlify.app"
title = "Red MMT Costa Rica"
copyright = "Copyright &copy; 2020 - Red MMT Costa Rica"
canonifyurls = true
theme = "tale"
paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true


DefaultContentLanguage = "es"

[languages]
  [languages.es]
    title = "Red MMT Costa Rica"
    languageName = "Spanish"
    weight = 1
